### ISSUE TITLE
Reorder menu items in "Edit Voice"

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#101]
I think we should reorder some of the menu items in "Edit voice" (e.g., to bring Edit Voice -> TGx -> Output Level closer to the beginning of the submenu, and to bring "Operator" closer to the beginning of its respective submenu).

Does the current order follow a particular logic we should stay at @rsta2? if not, what would I need to know if I wanted to reorder things a bit?

**Comment by rsta2** [comment]
TG1-8 must be the first entries in `s_MainMenu` and OP1-6 must be the first entries in `s_EditVoiceMenu`. This is because of the shortcut functions. Everything else can be changed.

**Comment by probonopd** [comment]
Thanks. I can live well with that restriction (didn't want to change that part anyway). Will do some subtle order changing experiments soon.

**Comment by probonopd** [comment]
Also updated the [documentation](https://github.com/probonopd/MiniDexed/wiki/Menu) accordingly.
This arrangement makes it quicker to do examples from the [books](https://github.com/probonopd/MiniDexed/wiki/Recommended-Resources#books).
