### ISSUE TITLE
Support CC messages for All Sound Off and All Notes Off

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#126]
* All Sound Off (CC 120) should trigger Synth_Dexed `void panic(void);`
* All Notes Off (CC 123) should trigger Synth_Dexed `void notesOff(void);`

**Comment by diysynth** [comment]
Thanks alot!

**Comment by probonopd** [comment]
it would be interesting to know how the TX802/TX816 behave here: Do they interpret this per Tone Generator or globally for all TGs?
