### ISSUE TITLE
Stereo panning

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#13]
Implement Stereo panning for each Dexed instance.

This is needed to create the characteristic "fat" sound known from the [TX816](https://www.vintagesynth.com/yamaha/tx816.php) and the [TX802](https://www.vintagesynth.com/yamaha/tx802.php).

**Comment by probonopd** [comment]
Looks like https://codeberg.org/dcoredump/MicroDexed/ has effects like this. Do you think these could be put into Synth_Dexed and hence made usable for MiniDexed @dcoredump?

**Comment by dcoredump** [comment]
Yes, I can do this. But give me some time :) I would like to add the MIDI processing code first.
