### ISSUE TITLE
Code for playing with standard ASCII-keyboard needed?

### ISSUE THREAD

**Issue by dcoredump** [probonopd/MiniDexed#19]
If not, the code should be dropped.

If we should need this, the code has to be fixed for keyUp() which isnt' currently implemented. Also there is no way to add velocity to those keyboards...

**Comment by probonopd** [comment]
I think it's useful for testing and debugging, for people who don't have a "known good" MIDI keyboard at hand. 
`keyUp()` would be nice indeed.
