### ISSUE TITLE
Some trouble with Classic MIDI In and old Roland Piano

### ISSUE THREAD

**Issue by Banana71** [probonopd/MiniDexed#356]
Hello,

i have some troubles with the classic midi input

after releasing a single note, the Roland RD-300 or the master keyboard Roland MKB-300 sends the command "CC: All Note off". MiniDexed then promptly cuts off all tones. The sustain pedal also has no effect. Other devices such as Waldorf Blofeld or the Roland JX-08, JD08 can handle it and can be played well with the RD-300.
Is there a way to filter the "CC All Note Off" command in MiniDexed.

Logfile vom Roland RD-300:
![Roland RD-300 Midi In](https://user-images.githubusercontent.com/104296205/192304199-f936fdd4-fb63-44f7-a7df-dd822d28a7f6.jpg)

If it ever works I'll put the MiniDexed in the RD-300 and MKB-300.

**Comment by probonopd** [comment]
According to https://community.cantabilesoftware.com/t/roland-d-50-midi-cc-123-all-notes-off/2157/6, certain Roland devices send CC 123 ("All Notes Off") when the last key is released. This is probably a bug or a misinterpretation of the MIDI standard by Roland at the time.

Apparently Roland owners just filter out CC 123.

We would need to make this configurable via `minidexed.ini`, since it is not desirable for non-Roland owners.

**Comment by Banana71** [comment]
Thank you very much Holger,
It's time to learn how to develop.

**Comment by diyelectromusic** [comment]
Interestingly this is a channel mode message, so only tone generators listening on a specific channel should respond to it.  The MIDI spec says that any instruments in Omni mode should ignore All Notes Off (see "channel mode messages: all notes off".  Also synths don't have to respond to it, it is optional...

So we ought to have something in the tone generators that checks for omni mode and ignore it if set...

**Comment by probonopd** [comment]
Please test [MiniDexed_2022-10-03-dc1a0e0](https://github.com/probonopd/MiniDexed/suites/8591707243/artifacts/384912002)

Set `IgnoreAllNotesOff=1` in `minidexed.ini`.

**Comment by Banana71** [comment]
It works very well, only sometimes there is hanging a tone. Maybe it's another problem with the old Roland hardware. Tomorrow I will take a little more time and investigate with MIDI-OX, among other things. 
Thank you very much

**Comment by probonopd** [comment]
Hanging tones could also be an issue on the Raspberry Pi software side. Which model of RPi are you using?

**Comment by Banana71** [comment]
I use a Raspberry Pi 3 Model B+

**Comment by probonopd** [comment]
Does it happen when you put a lot of load on the machine?

**Comment by Banana71** [comment]
I've played 4 TG's simultaneously with high polyphony on other Masterkeyboards connected via USB or classic MIDI In. So i exclude the Raspberry Pi in the problem.

**Comment by Banana71** [comment]
After I deleted the line "usbspeed=full" in the "cmdline.txt" file, it ran even more stably. 


> Please test [MiniDexed_2022-10-03-dc1a0e0](https://github.com/probonopd/MiniDexed/suites/8591707243/artifacts/384912002)
> 
> Set `IgnoreAllNotesOff=1` in `minidexed.ini`.

I would be very happy if you would apply your changes to "Main".

**Comment by probonopd** [comment]
Thanks, merged.
