### ISSUE TITLE
Optmize config.txt settings

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#36]
Should we do the following by default?

```
[all]
boot_delay=0
disable_splash=1
force_eeprom_read=0
gpu_mem=16
disable_overscan=1

[pi4]
# Optimized frequency settings for lower energy use/temperature on Pi 4
arm_freq=600
arm_freq_min=100
gpu_freq=100
over_voltage=-16
over_voltage_min=-16
```

**Comment by rsta2** [comment]
The settings for the RPi 4 are not necessary. It already runs at 600 Mhz. I wouldn't reduce that more. I'm generally not a friend of over- or under-clocking. It may work with one firmware, but not with the next. So you have to test everything carefully on any model to be sure. I don't think, this is worth the effort. Reducing the boot time makes sense.
