### ISSUE TITLE
MiniDexed cannot handle more than 40 performances

### ISSUE THREAD

**Issue by Banana71** [probonopd/MiniDexed#379]
There are 39 Perf.ini files in my performance folder. When I try to save a new performance, the Raspberry Pi crashes.
I've tried a few things with no success. (ID sorted, more than 40 performances in the folder)

[performance org.zip](https://github.com/probonopd/MiniDexed/files/10089372/performance.org.zip)
[performance 68.zip](https://github.com/probonopd/MiniDexed/files/10089371/performance.68.zip)

Make a back up from your data before copying my performance to the SD card.

**Comment by probonopd** [comment]
[This](https://github.com/probonopd/MiniDexed/pull/228/files#r1032076741) looks suspicious.

**Comment by probonopd** [comment]
Hi @Banana71. Can you please try, on a **test** miniSD card (that contains no important files), [MiniDexed_2022-11-25-961f76c](https://github.com/probonopd/MiniDexed/suites/9500389176/artifacts/450706221)?

**Comment by Banana71** [comment]
@probonopd It works. 1024 performances should be enough for now :-)

**Comment by probonopd** [comment]
Just ping me again when you are reaching the limit. Then we can increase it again :+1:
