### ISSUE TITLE
In MiniDexed.cpp Program/Bank Change ignore number of programs/banks allowed

### ISSUE THREAD

**Issue by diyelectromusic** [probonopd/MiniDexed#391]
Should BankSelectLSB bounds-check the provided MIDI value and limit to the number of loaded banks?
Similarly should ProgramChange limit to the number of voices per bank?

Alternatively should there be an option that if a ProgramChange message comes in over MIDI the values 0..127 map onto the first four banks of 32 voices each?  i.e.:
0..31 -> bank 1 voices 1-32
32..63 -> bank 2 voices 1-32
64..95 -> bank 3 voices 1-32
96..127 -> bank 4 voices 1-32

Of course this means that a MIDI sequence: Set Bank=2; Set Program = 4 would end up selecting bank 1, program 4 (as programs 1-32 map onto bank 1)... so this probably has to be configurable...

**Comment by BobanSpasic** [comment]
DX7 accepts ProgramChanges 0..31
DX7II accepts ProgramChanges 0..63 for internal memory and 64..127 for cartridge.

**Comment by diyelectromusic** [comment]
I'll have a play with this at some point, but I'm waiting for some of the current PRs to go through first so I'm not having to mess around merging minidexed.cpp... :)

**Comment by abscisys** [comment]
Why not to keep limiting prog change to 0 to 31 which is the size of a cartridge and have support bank select LSB and MSB to increase the number of supported cartridges to 2^ 14? 
If any interest, this is what I submitted as the PullRequest #395

**Comment by diyelectromusic** [comment]
The issue is that things like voices per bank requires the thing sending PC messages to know about the synth it is sending them too, whereas sending PC 0 to 127 is universal.

That isn't to say that recognising bank select shouldn't be improved, but for many cases recognising PC 0 to 127 gives access to much of the functionality for lots of users, and is also more "GM like" which again many will be familiar with.

Aside, if you want to allow for 2^14 banks, then I really, really think we have to limit the selection to "installed banks" not "potentially installed" banks... which is what is happening in https://github.com/probonopd/MiniDexed/pull/392
