### ISSUE TITLE
Serial MIDI sometimes drops messages when clock is running

### ISSUE THREAD

**Issue by JennToo** [probonopd/MiniDexed#416]
I have an SQ-64 and noticed that if I send my MIDI keyboard through the SQ-64 in "live" mode, notes will get randomly dropped and stuck. But if I directly connect my keyboard over MIDI, it works just fine.

I enabled MIDI traces and saw that the RPi is getting hammered with active sensing and clocking MIDI messages. If I disable MIDI clocking on the SQ-64 the issue doesn't seem to happen anymore.

However, the sequencer isn't really very useful without a clock, and I haven't found a way to let it run an internal clock without also transmitting it to the MIDI outs.

I'm suspecting the serial buffer gets too full when all the extra spam is coming in, and so random messages start getting lost. I'll do a little more investigating to see if I can diagnose it further.

Also not sure if it makes a difference, but this is an RPi 3 A+.

**Comment by JennToo** [comment]
Tracing through things, increasing the serial buffer sizes doesn't help. And it makes sense that it wouldn't, the buffer never seems to get anywhere close to full.

I'm now thinking this might be a state machine issue of some kind with the clock messages being misinterpreted.

**Comment by probonopd** [comment]
Thanks @JennToo for looking into this. Do you know a good way to test this, using only PC-side software like REAPER but no special MIDI hardware (which I don't have)?

**Comment by JennToo** [comment]
I haven't found a great way, no. I tried capturing through the SQ-64's USB-MIDI interface, but in that case it doesn't seem to intersperse the system real-time messages with the note events. Which also makes me worried that any attempt to try and send this with a USB MIDI device might also fail. I'm wondering if the USB MIDI protocol just packetizes all the events to avoid ever seeing this problem.

**Comment by diyelectromusic** [comment]
>  I'm wondering if the USB MIDI protocol just packetizes all the events to avoid ever seeing this problem.

I believe it does, yes, and the rate is so much quicker that these kinds of issues don't really apply in the same way (more here: https://github.com/probonopd/MiniDexed/pull/417#issuecomment-1384468946)

Kevin
