### ISSUE TITLE
Latest version of circle has moved the sound drivers

### ISSUE THREAD

**Issue by diyelectromusic** [probonopd/MiniDexed#421]
The sound drivers in circle have moved to their own directory.  This means updating minidexed.cpp, minidexed.h and Rules.mk to support the new libsound.a library in circle.

**Comment by diyelectromusic** [comment]
Looks like there is also an update to circle_stdlib_app.h which we copy from circle-stdlib (I don't know why we copy and not use it directly?).  The circle-stdlib version has changed the call to CGlueStdioInit as per this commit: https://github.com/smuehlst/circle-stdlib/commit/e880dc0ed1a2a3b8da6523383336532797c0be0e

We need to port that over to MiniDexed circle_stdlib.app.h too in order to use the develop version of circle_stdlib.

**Comment by probonopd** [comment]
Great point. Added that to the PR, fingers crossed :)

**Comment by diyelectromusic** [comment]
I think we've both done it - never mind!  The commit history is going to get very "noisy"!! :)

**Comment by probonopd** [comment]
> I think we've both done it

But yours is working - big difference ;-) :+1:

**Comment by diyelectromusic** [comment]
This update has been incorporated into https://github.com/probonopd/MiniDexed/pull/422 so I'm closing this issue.
