### ISSUE TITLE
"MIDI Message is shorter than 2 bytes" console error

### ISSUE THREAD

**Issue by diyelectromusic** [probonopd/MiniDexed#437]
Now that ActiveSensing and RT system messages are handled properly, any single byte messages trigger this message to be logged on the console due to https://github.com/probonopd/MiniDexed/blob/main/src/mididevice.cpp#L167

This message is probably on longer required?  The length test I'm not sure.  Ideally single byte messages would be parsed with everything else, but could also choose to ignore them here and still return prior to parsing (which is a valid strategy too).

Kevin

**Comment by probonopd** [comment]
Hi Kevin, should we just take the whole `if` block out then?

**Comment by diyelectromusic** [comment]
No, I think the test is still valid - we don't parse any messages less than 2 bytes long, we just don't need to shout about it :)
So I think it is a case of literally just removing the LOGERR message.

I'd have just done it but I need to refresh my source instance before I get back to anything in MiniDexed atm!

Kevin

**Comment by probonopd** [comment]
No problem, I'll comment out that message. Thanks @diyelectromusic
