### ISSUE TITLE
Ignore Bank Select and Program Change numbers that are not supported

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#45]
I didn't find this exact information in DX documentation but the "MX49/MX61 Data List" PDF says:

> Bank Select and Program Change numbers that are not supported by Yamaha will be ignored.

@rsta2 you are already doing this for the rotary encoder and it seems like we should be doing the same for MIDI Bank Select and Program Change messages.

**Comment by rsta2** [comment]
We do. Program Change messages are allowed for programs 0..31 (1..32 for the user) and Bank Selects from banks 0..127 (1..128 for the user). All other messages will be ignored. Bank Select MSB will be totally ignored at the moment.

**Comment by probonopd** [comment]
My bad. Made a mistake in testing. The "Take off" preset had me tricked - it is so silent in the beginning that I thought I was hearing nothing when Iin fact it was working.

**Comment by rsta2** [comment]
No problem.
