### ISSUE TITLE
Bank wrap-around on voice change not working problem for first and last banks

### ISSUE THREAD

**Issue by diyelectromusic** [probonopd/MiniDexed#491]
I think it is a problem with m_nNumHighestBank in the SysFileLoader as a consequence of moving to 1-indexed numbered banks.  More details to follow...

Update: Yes, this is the issue.  The bank selection in uimenu.cpp is also not working properly for cases where there are skipped bank numbers.

Kevin

**Comment by probonopd** [comment]
Thanks for finding and for fixing this issue Kevin.
