### ISSUE TITLE
classic midi to minidexed

### ISSUE THREAD

**Issue by Synthfreek** [probonopd/MiniDexed#497]
Dear friends, please help. I try to built a midi in for the raspberry pi 3b that is running minidexed (the dx 7's)
I want to use a midikeyboard that has only the classic 5-pin midi
I did built a midi in like descripted on https://diyelectromusic.files.wordpress.com/2021/02/diy-midi-receive-3.3v-v2_schem-1.png but it seems not to work. do I have to change something in the ini code? 
any suggestions are welcome
thanx, kind regards, Wim (the Netherlands)

**Comment by diyelectromusic** [comment]
MIDI should "just work", but there is a setting you can enable to make sure MIDI data is getting through. Set MIDIDumpEnabled=1 in the config file and ensure there is a video output (e.g. HDMI) connected (not an LCD).

Then it is a case of check and double check the circuit really.  Can you provide a hi-res photo so we could have a look to see if we can spot anything?

The thing that almost always gets me - even now, and I've built more MIDI circuits than I can remember - is the pinouts for the DIN sockets.  I still get 4 and 5 wrong!

Kevin

**Comment by Banana71** [comment]
Some good photos of your circuit would help 👀

**Comment by Synthfreek** [comment]
![20230603_163416](https://github.com/probonopd/MiniDexed/assets/130309861/2dc264b1-265f-4a31-adbb-d3cc3764e909)
![20230603_163314](https://github.com/probonopd/MiniDexed/assets/130309861/b8f67520-8935-49a2-bd46-7a9b657f37e8)
![20230603_163350](https://github.com/probonopd/MiniDexed/assets/130309861/f508e967-a3c4-4c64-aa3f-d132f75ec2d4)

**Comment by diyelectromusic** [comment]
Well I'm not sure I can make out which pin is which on that DIN Connector!  I just have to assume you've checked and double checked.  The rest of the circuit looks ok, (I trust white is connected to GND - its a little hard to see).  So assuming nothing weird is happening on the solderless breadboard (they are quite unreliable at times I'm afraid), then all I can suggest is enabling MIDI debugging and starting to look at the signal at different places as I suggested in my previous comments https://github.com/probonopd/MiniDexed/discussions/279#discussioncomment-6032166

Kevin

**Comment by Gustavomurta** [comment]
Hi Synthfreek,
Analyzing the photo of the MIDI RCA-5 female connector, confirm that the blue wire is pin 5 and the red wire is pin 4. See if you can see the pin numbering on the connector.

![MIDI RCA-5 demale wire view teste](https://github.com/probonopd/MiniDexed/assets/4587366/5c1b1394-2dcf-4024-b34c-edf9578abe1e)

**Comment by Gustavomurta** [comment]
Another diagram made by me.

![miniDexed MIDIN edited](https://github.com/probonopd/MiniDexed/assets/4587366/a358b3dc-bcb4-469e-94a6-7e3d36f39b03)

**Comment by Synthfreek** [comment]
I will try the other way around. The picture may look confusing because I bended the unused pins to the outside.Op 20 jul. 2023 03:11 schreef Jose Gustavo Abreu Murta ***@***.***>:
Hi Synthfreek,
Analyzing the photo of the MIDI RCA-5 female connector, confirm that the blue wire is pin 5 and the red wire is pin 4. See if you can see the pin numbering on the connector.
