### ISSUE TITLE
Should performances be in their own (sub)project on Github?

### ISSUE THREAD

**Issue by diyelectromusic** [probonopd/MiniDexed#571]
It's great to see the performances continually evolving, but having so many files changing so much does make managing branches with code in development quite challenging.

Is it worth creating another repository for them so they can be maintained independently?  Perhaps it would be included in the main repository as a submodule or maybe they should be pulled into the build when images are created?

I don't really know enough about how Github works to know what is the best solution, but having so many files changing in a way that doesn't affect the code but seems to really confuse the merging/syncing process does seem to add quite a bit of overhead to anyone updating code.  Although, I'd be the first to admit I'm perhaps not using Github in the most optimal way!

Kevin

**Comment by BobanSpasic** [comment]
@diyelectromusic 
You have my vote

**Comment by Banana71** [comment]
My thoughts so far were that I would put together 128 “factory performances” and then they would permanently belong to the project. And if there is an opportunity to work with multiple performance folders or performance banks, I wanted to create additional topic-related performance banks.

I created a performance update as a new repository. I hope it makes your work easier.

https://github.com/Banana71/Soundplantage

I think @probonopd  should link this into his miniDexed project as submodule. !?

**Comment by BobanSpasic** [comment]
My conversions from DX/TX-series will go here:
https://github.com/BobanSpasic/MDX_Vault

**Comment by Banana71** [comment]
wow, that's nice. @BobanSpasic 
 Do you want to include the TX816 Performances?  Then all Yamaha Performances are in one place.

https://github.com/probonopd/MiniDexed/files/10717692/Performance.TX816.Factory.zip

**Comment by BobanSpasic** [comment]
Thanks @Banana71 , I'll include TX816 too.
I still have a loooot of banks to translate. This commit today is just the beginning.
I've got the memory dumps of DX7II cartridges like Decay, Percussion, Plucked etc.

**Comment by probonopd** [comment]
> Can you make one example script for me

Check this:
https://github.com/BobanSpasic/MDX_PerfConv/pull/9

**Comment by probonopd** [comment]
> I am fighting with conversion from SoundDiver 3 files to SysEx at the moment

You probably already have found this:

https://gist.github.com/arteme/76f59209db3fe263c82ee151e35a1723

[MIDI-OX](http://www.midiox.com/moxdown.htm) is said to be able to open SoundDiver lib files and save them as syx, although I have not tried it.

**Comment by probonopd** [comment]
Yes, I think we should map file names to MIDI numbers for performances (and voices).
How about folders being numbered and being mapped to MIDI banks in the same way?

**Comment by diyelectromusic** [comment]
> How about folders being numbered and being mapped to MIDI banks in the same way?

Well, for all the issues I list about the use of subdirectories, whilst ideally I think this would be a good way to go, I think it will be a lot of complications in the code for very little real gain.

**Comment by BobanSpasic** [comment]
About SysEx - the nearest device to MiniDexed is TX802, but this would need a re-write from scratch. Voices need to be in DX7II format and performances something like TX802 Performances, where TX802 uses a very ugly format for performance files.
SynthDexed engine is capable of this, but MiniDexed needs to be rewritten.
By using DX7II format for voices, all the controller settings (ModWheel, Aftertouch etc.), Portamento, Poly/Mono are then a part of the voice. 
NoteLimits, MidiChannel, Pan, and additional MiniDexed parameters for effects - part of the performance.

I would not go for it. 

What we could optimize is:
- have a directory "cartridges" instead of sysex and performances
- cartridge contains subfolders (actual "cartridges")
- every "cartridge" contains sysex banks, and performances using these banks
- now we can strip voice data from the performance files, because the linked banks are provided in the same directory
- deploying voices and performances is now deploying the directory content of the "cartridge"

**Comment by probonopd** [comment]
Actually what I like about the current format of our performances is that they contain the needed voices, makes it easy to share/move just 1 file, and you don't have to keep track of matching the correct voices with the corresponding performances in the filesystem.

**Comment by Banana71** [comment]
>It's not a probem to have a B-Side folder in the repository, but given your explanation let's not include it in the MiniDexed download.

Does that mean I can create additional folders, but you only pick up what you need?
And please include the miniDexed Performance List.pdf in the root directory.

**Comment by probonopd** [comment]
> Does that mean I can create additional folders, but you only pick up what you need?

Yes, as long there is one folder that I should pick. Ideally the folder would be called "performances" and everything that should not be shipped would be in folders outside of that folder.

**Comment by diyelectromusic** [comment]
btw - should @Banana71's performance github project be included in the main MiniDexed github too? I don't really know how these things work, but it is certainly useful to be able to get from MiniDexed to the list of performances from the same github starting point.

**Comment by probonopd** [comment]
> should @Banana71's performance github project be included in the main MiniDexed github too? 

It already is:

https://github.com/probonopd/MiniDexed/blob/c6325cd04c7e1c4623173039865f96c9a83738c9/.github/workflows/build.yml#L73-L74

**Comment by diyelectromusic** [comment]
It is included in the build, but not in the project...?

**Comment by probonopd** [comment]
It is not a git submodule if you mean that by "included in the project". To be honest, I find git submodules a pain and try to avoid them if not absolutely needed.

**Comment by diyelectromusic** [comment]
Ok - it was more that it allows one to click through from the main project to any sub-projects easily for browsing the repositories :)

I guess a prominent link in the readme would do just as well!

Kevin

**Comment by probonopd** [comment]
Good idea, done!

**Comment by diyelectromusic** [comment]
Closing this now as I think it is pretty much covered by https://github.com/probonopd/MiniDexed/pull/581

If elements are still outstanding, then I suggest they are picked up as new issues.

Kevin
