### ISSUE TITLE
Rename "MIDI Gadget MIDI 1" to "MiniDexed MIDI 1"

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#587]
Currently, REAPER (on WINE) shows MiniDexed as "MIDI Gadget MIDI 1".

We should rename "MIDI Gadget MIDI 1" to "MiniDexed MIDI 1" if possible to make it easier to find.

**Comment by probonopd** [comment]
Is it coming from Circle here?

https://github.com/rsta2/circle/blob/c21f2efdad86c1062f255fbf891135a2a356713e/lib/usb/gadget/usbmidigadget.cpp#L166

**Comment by Banana71** [comment]
The idea is very good. My other MIDI devices are also displayed more clearly.
Other manufacturers do not agree whether the name "MIDI" should still be in the name. But "MiniDexed MIDI" is also great.

![Screenshot 2023-12-09 173803](https://github.com/probonopd/MiniDexed/assets/104296205/46bae434-1436-4cde-86d8-41142590d2f2)

**Comment by probonopd** [comment]
I am on it.

**Comment by probonopd** [comment]
Build for testing:
[MiniDexed_2023-12-09-a1518d6](https://github.com/probonopd/MiniDexed/suites/18901668257/artifacts/1103715663)

**Comment by probonopd** [comment]
Also, we should probably disable the MIDI output as it is currently unused.

**Comment by diyelectromusic** [comment]
No, I really disagree with patching code like this.  If we want it changing we need to log an issue in circle to make it configurable. This kind of build-time patching will just make things very hard to maintain - and let's face it, with quite a few people pitching in changes over the evolution of MiniDexed, it's already quite hard to maintain the codebase... (hence my cautious approach with the performance subdirectories)

Kevin

**Comment by probonopd** [comment]
I have opened https://github.com/rsta2/circle/issues/416.

**Comment by probonopd** [comment]
@diyelectromusic Do you think you could change this PR to follow https://github.com/rsta2/circle/issues/416#issuecomment-1848919646?

**Comment by diyelectromusic** [comment]
I'll have a look at some point. I'm still chewing over performance things at the moment.

Kevin
