### ISSUE TITLE
Question about  "Add note limits and shift to performance.ini" (Commit #99cefaefd348818cc5152b3041ec6f1d186f0e3c)

### ISSUE THREAD

**Issue by dcoredump** [probonopd/MiniDexed#60]
Just a question: Is `m_nNoteShift[]` currently used? Synth_Dexed has methods for this:
```
void setTranspose(uint8_t transpose);
uint8_t getTranspose(void);
```

**Comment by rsta2** [comment]
Yes, it's a global note shift, which is applied to all Dexed instances. The local transpose parameter is still valid. This is the same behavior, which the TX802 has: one transpose in each TG and one global parameter in the performance.

**Comment by rsta2** [comment]
Correction: This note shift parameter in the performance is there for each TG separately. But it is independent from the transpose parameter of the voice. Actually the two parameters will be added together. See pg. 16 "5. Midi Note Shift" in the TX802 Manual.

**Comment by dcoredump** [comment]
Ahhh, ok. Thanks!
