### ISSUE TITLE
Settings for effects in performance.ini

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#64]
Let's store the settings for the effects (e.g., reverb) in `performance.ini` so that one can edit them.

**Comment by rsta2** [comment]
OK, will do so for the reverb settings.

**Comment by probonopd** [comment]
And the compressor?

**Comment by rsta2** [comment]
Too.

**Comment by rsta2** [comment]
Implemented by #69.

**Comment by probonopd** [comment]
Cool!

How hard would it be to implement a "Save" function that would write back to the `performance.ini` file?

**Comment by rsta2** [comment]
Requires some effort, but is possible.

**Comment by rsta2** [comment]
If it's OK, I would concentrate on the "Save performance" function now.
