### ISSUE TITLE
LCD: Reverse click and double-click

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#65]
In computer interfaces, double-click is for opening stuff. So I think it would be more natural to double-click in order to go down in the menu hierarchy ("open a submenu"), and to single-click to go up ("close the submenu"). Wdyt @rsta2?

**Comment by rsta2** [comment]
That's right and can be easily changed. Will do so.

**Comment by rsta2** [comment]
This has been implemented by #67.

**Comment by probonopd** [comment]
Works well for me and indeed feels more natural. Thanks!

(If we ever get to building a PCB, maybe we'll want an extra button for that.)
