### ISSUE TITLE
Voice initialize function

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#75]
Reading 

> FM Theory & Applications: By Musicians for Musicians 
by Dr. John Chowning and David Bristow
ISBN 4636174828

there are lots of example voices that help one to learn FM synthesis. They start by using the "VOICE INIT" button on the DX7. "This function sets up the basic voice data for creating new voices".

Maybe we should have a similar function, e.g., under

TG X -> Edit Voice -> Initialize

It should load the initialization default values:

https://github.com/asb2m10/dexed/blob/11ae4d7ef597b2d52f45e59ab56b342252d0bd88/Source/PluginData.cpp#L230-L239

```
void DexedAudioProcessor::resetToInitVoice() {
    const char init_voice[] =
      { 99, 99, 99, 99, 99, 99, 99, 00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 7,
        99, 99, 99, 99, 99, 99, 99, 00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 7,
        99, 99, 99, 99, 99, 99, 99, 00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 7,
        99, 99, 99, 99, 99, 99, 99, 00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 7,
        99, 99, 99, 99, 99, 99, 99, 00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 7,
        99, 99, 99, 99, 99, 99, 99, 00, 0, 0, 0, 0, 0, 0, 0, 0, 99, 0, 1, 0, 7,
        99, 99, 99, 99, 50, 50, 50, 50, 0, 0, 1, 35, 0, 0, 0, 1, 0, 3, 24,
        73, 78, 73, 84, 32, 86, 79, 73, 67, 69 };
```

**Comment by rsta2** [comment]
"Edit Voice" and "Initialize" does not fit on one LCD line too. Better "TG#" > "Init Voice" or "TG#" > "Edit Voice" > "Init". Everything else should work.

**Comment by probonopd** [comment]
"TG#" > "Edit Voice" > "Init" 
makes most sense for me.

**Comment by rsta2** [comment]
Yes, but this does not make sense in my opinion, if we do not have a function to save the edited voice to a voice bank .syx file on the SD card?

**Comment by probonopd** [comment]
Indeed I could imagine that sooner or later that feature might be requested by someone.

**Comment by rsta2** [comment]
I will have a look at the "Init" function, when I have some break from searching for the USB issue cause.

**Comment by probonopd** [comment]
Agree. We should use 2. for the purpose.

And we can remove 1. because we don't need ROM1A hardcoded anymore.

But if the user has no `.syx` files loaded at all, then there should be at least one good-sounding default voice. Would that be 3.?

**Comment by rsta2** [comment]
Yes, 2. would be used for the "Init" function in the UI and 3. for all voices in all voice banks, when there isn't any loaded voice bank available. Class `CSysExFileLoader` can be easily changed for this purpose.

**Comment by probonopd** [comment]
As a workaround, I found that e.g., http://dxsysex.com/SYSEX_DX7/Guest/ENO.syx contains the init voice on the "empty" slots of the bank.
