### ISSUE TITLE
Shortcut for switching between OPx

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#81]
It would be neat if we could have a shortcut for switching between OPx, like we have a shortcut for switching between TGx.

We could use the same "gesture": keep-button-pressed-and-rotate-knob. If there is "TGx" in the upper-right corner of the screen, it would go through the TGs (as it is now). If there is "OPx" in the upper-right corner of the screen, it would go through the OPs (new).

Wdyt @rsta2

**Comment by rsta2** [comment]
May be possible. I will have a look on it.

**Comment by rsta2** [comment]
See #84.
