### ISSUE TITLE
Osc Mode display values behave differently

### ISSUE THREAD

**Issue by probonopd** [probonopd/MiniDexed#91]
Accroding to the DX7 manual,

> If MODE is set to FIXED FREQ (HZ), COARSE adjustment is possible in four steps-1, 10, 100 and 1000. FINE adjustment is possible from 1 to 9.772 times.

Currently in MiniDexed, setting _Osc Mode_ to _fixed_ does not seem to have any impact on the behavior of _Freq Coarse_ and _Freq Fine_.

**Comment by rsta2** [comment]
Can this be caused by the missing refresh function similar to #80?

**Comment by probonopd** [comment]
I thought the menu entries would change when one switches __Osc Mode_ to _Fixed_, but __Freq Coarse__ and __Freq Fine__ still have `<-1->`. Do I undertsand it wrong?

**Comment by rsta2** [comment]
No, the menu entries do not change. Freq Coarse and Fine are always there, despite of the Osc Mode setting.

**Comment by probonopd** [comment]
Doing more experiments, I can confirm that both modes are working.

But what is shown in the display is very different from what a DXx/TXxxx would show, and hence I can't do the examples from the books with MiniDexed at the moment.

**Comment by probonopd** [comment]
I think this is how it _should_ be:

* Freq Coarse: If Osc Mode is set to Ratio, the frequency ratio can be set from one half (0.5 times) to 32 times, default is 1 _-  these values should be shown in the display?_ If Osc Mode is set to Fixed, one of the following frequencies can be selected: 1, 10, 100, and 1000 Hz _-  these values should be shown in the display?_
* Freq Fine_ If Osc Mode is set to Ratio, the frequency set by Freq Coarse can be adjusted from 1 to 1.99 times _-  these values should be shown in the display?_ If Osc Mode is set to Fixed, the frequency set by Freq Coarse can be adjusted from 1 to 9.772 times _-  these values should be shown in the display?_

**Comment by probonopd** [comment]
Reference:
[For the intended ](https://github.com/probonopd/MiniDexed/wiki/Exercises#exercise-17-fixed-mode)

**Comment by rsta2** [comment]
Not that simple to implement this, like it may look like. Currently the UI is designed for the assumption, that there are no dependencies between different parameters, when deciding, how to implement their values. I think about, how this can be changed.

**Comment by probonopd** [comment]
Ah, I understand. No hurry! In the meantime, maybe we should have the menus print both values (variable and fixed)?

**Comment by rsta2** [comment]
I would like to know, how is the exact mapping from the parameter range 0-31 for coarse to 0.5 to 32 times for ratio and 1, 10, 100, 1000 Hz for fixed? Respectively how is the mapping from 0-99 for fine to 1 to 1.99 times for ratio and 1 to 9.772 times for fixed. At the moment the raw parameter values 0-31 and 0-99 are shown.

**Comment by probonopd** [comment]
Ratio:
* **Coarse**: 0.5, 1, 2, ... 31
* **Fine**: 1, 1.01, ... 1.99 times the selected **Course** value (if it is too much work to implement this, then show the unmultiplied values)

Fixed:
* **Coarse**: 1 Hz, 10 Hz, 100 Hz, 1000 Hz (strangely the knob in Dexed repeats these a couple of times, bug?)
* **Fine**: 1 Hz, 1.02329 Hz, 1.04713 Hz, 1.07152 Hz, ... 9.77237 Hz times the selected **Course** value (if it is too much work to implement this, then show the unmultiplied values). I don't know where these odd values are coming from, maybe @asb2m10 can tell us?

**Comment by rsta2** [comment]
See #123.

**Comment by probonopd** [comment]
Testing asap. Thank you!

**Comment by probonopd** [comment]
Coarse in Fixed mode repeats the same values a couple of times, but I think that's more a curiosity than a bug. No need to invest time to change this imho.

**Comment by probonopd** [comment]
Closed in https://github.com/probonopd/MiniDexed/commit/43e0c1872c576dcbb217e2c54a51cee12049b112

Thanks @rsta2

**Comment by probonopd** [comment]
Fwiw, I found the official values documented in the TX816 manual:

![image](https://user-images.githubusercontent.com/2480569/164335085-1f452a59-dac4-4240-b18e-82076ef0e3d6.png)
